#端口号
server:
  port: 8888
  context-path: /elst/
#数据库链接设置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elst?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver

#整合Mybatis
mybatis:
  type-aliases-package: com.securityjwtdemo.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/SqlSessionFactory.xml
debug: true
