server:
  port: 9091

spring:
  application:
    name: spring-boot-jpa
  datasource:
    url: jdbc:mysql://localhost:3306/abtest?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true