server:
  port: 8081
spring:
  application:
    name: spring-boot-security
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-security?serverTimezone=UTC&characterEncoding=utf-8&useSSL=true
    username: root
    password: F&&@19900415x
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    check-template-location: false
debug: false

jwt:
  secret: mcp_admin_1626260693000
  ttl: 1800000