server:
  port: 8888
spring:
  application:
    name: spring-boot-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lovejobs/spring-boot-config-file

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.11.85:8761/eureka/

